/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLoading: typeof import('./src/components/ElLoading.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElProgressLoading: typeof import('./src/components/ElProgressLoading.vue')['default']
    IconAbout: typeof import('./src/components/icons/IconAbout.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconQQ: typeof import('./src/components/icons/IconQQ.vue')['default']
    IconScan: typeof import('./src/components/icons/IconScan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElLoading: typeof import('./src/components/ElLoading.vue')['default']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElProgressLoading: typeof import('./src/components/ElProgressLoading.vue')['default']
  const IconAbout: typeof import('./src/components/icons/IconAbout.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
  const IconQQ: typeof import('./src/components/icons/IconQQ.vue')['default']
  const IconScan: typeof import('./src/components/icons/IconScan.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}