name = "ay-api"
compatibility_date = "2026-06-29"
main = "src/index.js"
keep_vars = true
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "kv", id = "483f0fad0c2841a2888c72869e041dfd" }
]

[[ratelimits]]
name = "limiter"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 50
  period = 10

[assets]
binding = "assets"
directory = "../api-assets"
run_worker_first = true

[[d1_databases]]
binding = "db" 
database_name = "api_db" 
database_id = "aa999f5d-188b-4fe7-83be-24ec7d521060" 

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
WORKFLOW_ID = "scheduled-publish.yml"
OWNER = "AeYunDian"
REPO = "aeyundian.github.io"
BRANCH = "main"